### ISSUE TITLE
Remove stickytape dependency for AWS

### ISSUE THREAD

**Issue by whiz-Tuhin** [dream-lab/XFaaS#4]
AWS runner template generation currently uses stickytape for generating intermediate runners.
The purpose of stickytape being to pull all the dependencies (nested user defined module imports) together into one single file.
We then use jinja on this file to create the executable runner.

We might be able to achieve the same behaviour without stickytape by fixing the way we add the imports in python for the user defined modules / routines.

Fix is required for this.

**Comment by godofpsychos** [comment]
This issue is fixed in async-faas branch
